{
 "title": "Kubernetes",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "group",
    "query": {
     "query": "label_values(apiserver_request_duration_seconds_bucket, group)"
    }
   },
   {
    "name": "version",
    "label": "version",
    "query": {
     "query": "label_values(apiserver_request_duration_seconds_bucket{group=~\"$group\"}, version)"
    }
   },
   {
    "name": "resource",
    "label": "resource",
    "query": {
     "query": "label_values(apiserver_request_duration_seconds_bucket{group=~\"$group\", version=~\"$version\"}, resource)"
    }
   },
   {
    "name": "verb",
    "label": "verb",
    "query": {
     "query": "label_values(apiserver_request_duration_seconds_bucket{group=~\"$group\", version=~\"$version\", resource=~\"$resource\"}, verb)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_status_phase, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "request duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "APIServer request duration -- $group/$version/$resource, $verb",
     "type": "heatmap",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by (le) (rate(apiserver_request_duration_seconds_bucket{resource=~\"$resource\", verb=~\"$verb\", version=~\"$version\", verb=~\"$verb\"}[5m])) ",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request queue performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "apiserver queue",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "apiserver_current_inqueue_requests",
       "legendFormat": "In queue: {{request_kind}}"
      },
      {
       "expr": "rate(apiserver_dropped_requests_total[15m])",
       "legendFormat": "Dropped rate: {{request_kind}}"
      },
      {
       "expr": "apiserver_current_inflight_requests",
       "legendFormat": "In flight: {{request_kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod status phase",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by (namespace, phase) (kube_pod_status_phase{namespace=~\"$namespace\"})",
       "legendFormat": "{{namespace}}/{{phase}}"
      }
     ]
    }
   ]
  }
 ]
}