{
 "title": "Nginx ingress controller",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_bytes_sent_bucket{}, namespace)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(nginx_ingress_controller_bytes_sent_bucket{namespace=~\"$namespace\"}, service)"
    }
   },
   {
    "name": "path",
    "label": "path",
    "query": {
     "query": "label_values(nginx_ingress_controller_bytes_sent_bucket{namespace=~\"$namespace\",service=~\"$service\"}, path)"
    }
   },
   {
    "name": "method",
    "label": "method",
    "query": {
     "query": "label_values(nginx_ingress_controller_bytes_sent_bucket{namespace=~\"$namespace\",service=~\"$service\",path=~\"$path\"}, method)"
    }
   },
   {
    "name": "status",
    "label": "status",
    "query": {
     "query": "label_values(nginx_ingress_controller_bytes_sent_bucket{namespace=~\"$namespace\",service=~\"$service\",path=~\"$path\", method=~\"$method\"}, status)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Nginx ingress controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes sent",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (rate(nginx_ingress_controller_bytes_sent_bucket{method=~\"$method\", namespace=~\"$namespace\", path=~\"$path\", service=~\"$service\", status=~\"$status\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Upstream latency quantiles (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "nginx_ingress_controller_ingress_upstream_latency_seconds{namespace=~\"$namespace\",service=~\"$service\"}",
     "legendFormat": "{{quantile}} ({{namespace}}/{{service}})"
    }
   ]
  },
  {
   "title": "Response duration (seconds)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{method=~\"$method\", namespace=~\"$namespace\", path=~\"$path\", service=~\"$service\", status=~\"$status\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le) (rate(nginx_ingress_controller_response_size_bucket{method=~\"$method\", namespace=~\"$namespace\", path=~\"$path\", service=~\"$service\", status=~\"$status\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request duration (seconds)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=~\"$method\", namespace=~\"$namespace\", path=~\"$path\", service=~\"$service\", status=~\"$status\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (le) (rate(nginx_ingress_controller_request_size_bucket{method=~\"$method\", namespace=~\"$namespace\", path=~\"$path\", service=~\"$service\", status=~\"$status\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Process connections by state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "nginx_ingress_controller_nginx_process_connections",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_nginx_process_cpu_seconds_total[5m])",
     "legendFormat": "seconds"
    }
   ]
  }
 ]
}