// Code generated by "stringer -type=IPKind"; DO NOT EDIT.

package serviceevents

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClusterIP-0]
	_ = x[ExternalIP-1]
	_ = x[LoadBalancerIP-2]
}

const _IPKind_name = "ClusterIPExternalIPLoadBalancerIP"

var _IPKind_index = [...]uint8{0, 9, 19, 33}

func (i IPKind) String() string {
	if i < 0 || i >= IPKind(len(_IPKind_index)-1) {
		return "IPKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IPKind_name[_IPKind_index[i]:_IPKind_index[i+1]]
}
