// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package localnetv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// EndpointsClient is the client API for Endpoints service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EndpointsClient interface {
	// Returns all the endpoints for this node.
	Next(ctx context.Context, in *NextFilter, opts ...grpc.CallOption) (Endpoints_NextClient, error)
}

type endpointsClient struct {
	cc grpc.ClientConnInterface
}

func NewEndpointsClient(cc grpc.ClientConnInterface) EndpointsClient {
	return &endpointsClient{cc}
}

var endpointsNextStreamDesc = &grpc.StreamDesc{
	StreamName:    "Next",
	ServerStreams: true,
}

func (c *endpointsClient) Next(ctx context.Context, in *NextFilter, opts ...grpc.CallOption) (Endpoints_NextClient, error) {
	stream, err := c.cc.NewStream(ctx, endpointsNextStreamDesc, "/localnetv1.Endpoints/Next", opts...)
	if err != nil {
		return nil, err
	}
	x := &endpointsNextClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Endpoints_NextClient interface {
	Recv() (*NextItem, error)
	grpc.ClientStream
}

type endpointsNextClient struct {
	grpc.ClientStream
}

func (x *endpointsNextClient) Recv() (*NextItem, error) {
	m := new(NextItem)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EndpointsService is the service API for Endpoints service.
// Fields should be assigned to their respective handler implementations only before
// RegisterEndpointsService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type EndpointsService struct {
	// Returns all the endpoints for this node.
	Next func(*NextFilter, Endpoints_NextServer) error
}

func (s *EndpointsService) next(_ interface{}, stream grpc.ServerStream) error {
	m := new(NextFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return s.Next(m, &endpointsNextServer{stream})
}

type Endpoints_NextServer interface {
	Send(*NextItem) error
	grpc.ServerStream
}

type endpointsNextServer struct {
	grpc.ServerStream
}

func (x *endpointsNextServer) Send(m *NextItem) error {
	return x.ServerStream.SendMsg(m)
}

// RegisterEndpointsService registers a service implementation with a gRPC server.
func RegisterEndpointsService(s grpc.ServiceRegistrar, srv *EndpointsService) {
	srvCopy := *srv
	if srvCopy.Next == nil {
		srvCopy.Next = func(*NextFilter, Endpoints_NextServer) error {
			return status.Errorf(codes.Unimplemented, "method Next not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "localnetv1.Endpoints",
		Methods:     []grpc.MethodDesc{},
		Streams: []grpc.StreamDesc{
			{
				StreamName:    "Next",
				Handler:       srvCopy.next,
				ServerStreams: true,
			},
		},
		Metadata: "pkg/api/localnetv1/services.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewEndpointsService creates a new EndpointsService containing the
// implemented methods of the Endpoints service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewEndpointsService(s interface{}) *EndpointsService {
	ns := &EndpointsService{}
	if h, ok := s.(interface {
		Next(*NextFilter, Endpoints_NextServer) error
	}); ok {
		ns.Next = h.Next
	}
	return ns
}

// UnstableEndpointsService is the service API for Endpoints service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableEndpointsService interface {
	// Returns all the endpoints for this node.
	Next(*NextFilter, Endpoints_NextServer) error
}
