// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/api/localnetv1/services.proto

package localnetv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Protocol int32

const (
	Protocol_UnknownProtocol Protocol = 0
	Protocol_TCP             Protocol = 1
	Protocol_UDP             Protocol = 2
	Protocol_SCTP            Protocol = 3
)

var Protocol_name = map[int32]string{
	0: "UnknownProtocol",
	1: "TCP",
	2: "UDP",
	3: "SCTP",
}

var Protocol_value = map[string]int32{
	"UnknownProtocol": 0,
	"TCP":             1,
	"UDP":             2,
	"SCTP":            3,
}

func (x Protocol) String() string {
	return proto.EnumName(Protocol_name, int32(x))
}

func (Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2ce8e7107c99e043, []int{0}
}

type NextFilter struct {
	// Unique instance ID to manage proxy restarts
	InstanceID uint64 `protobuf:"varint,1,opt,name=InstanceID,proto3" json:"InstanceID,omitempty"`
	// The latest revision we're aware of (0 at first)
	Rev                  uint64   `protobuf:"varint,2,opt,name=Rev,proto3" json:"Rev,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NextFilter) Reset()         { *m = NextFilter{} }
func (m *NextFilter) String() string { return proto.CompactTextString(m) }
func (*NextFilter) ProtoMessage()    {}
func (*NextFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce8e7107c99e043, []int{0}
}

func (m *NextFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextFilter.Unmarshal(m, b)
}
func (m *NextFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextFilter.Marshal(b, m, deterministic)
}
func (m *NextFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextFilter.Merge(m, src)
}
func (m *NextFilter) XXX_Size() int {
	return xxx_messageInfo_NextFilter.Size(m)
}
func (m *NextFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_NextFilter.DiscardUnknown(m)
}

var xxx_messageInfo_NextFilter proto.InternalMessageInfo

func (m *NextFilter) GetInstanceID() uint64 {
	if m != nil {
		return m.InstanceID
	}
	return 0
}

func (m *NextFilter) GetRev() uint64 {
	if m != nil {
		return m.Rev
	}
	return 0
}

type NextItem struct {
	// Filter to use to get the next notification (first item in stream)
	Next *NextFilter `protobuf:"bytes,1,opt,name=Next,proto3" json:"Next,omitempty"`
	// A service endpoints item (any item after the first)
	Endpoints            *ServiceEndpoints `protobuf:"bytes,2,opt,name=Endpoints,proto3" json:"Endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NextItem) Reset()         { *m = NextItem{} }
func (m *NextItem) String() string { return proto.CompactTextString(m) }
func (*NextItem) ProtoMessage()    {}
func (*NextItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce8e7107c99e043, []int{1}
}

func (m *NextItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextItem.Unmarshal(m, b)
}
func (m *NextItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextItem.Marshal(b, m, deterministic)
}
func (m *NextItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextItem.Merge(m, src)
}
func (m *NextItem) XXX_Size() int {
	return xxx_messageInfo_NextItem.Size(m)
}
func (m *NextItem) XXX_DiscardUnknown() {
	xxx_messageInfo_NextItem.DiscardUnknown(m)
}

var xxx_messageInfo_NextItem proto.InternalMessageInfo

func (m *NextItem) GetNext() *NextFilter {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *NextItem) GetEndpoints() *ServiceEndpoints {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type ServiceEndpoints struct {
	Namespace            string             `protobuf:"bytes,1,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Name                 string             `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Type                 string             `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	IPs                  *ServiceIPs        `protobuf:"bytes,100,opt,name=IPs,proto3" json:"IPs,omitempty"`
	Ports                []*PortMapping     `protobuf:"bytes,101,rep,name=Ports,proto3" json:"Ports,omitempty"`
	Subsets              []*EndpointsSubset `protobuf:"bytes,102,rep,name=Subsets,proto3" json:"Subsets,omitempty"`
	AllIPsV4             []string           `protobuf:"bytes,103,rep,name=AllIPsV4,proto3" json:"AllIPsV4,omitempty"`
	AllIPsV6             []string           `protobuf:"bytes,104,rep,name=AllIPsV6,proto3" json:"AllIPsV6,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ServiceEndpoints) Reset()         { *m = ServiceEndpoints{} }
func (m *ServiceEndpoints) String() string { return proto.CompactTextString(m) }
func (*ServiceEndpoints) ProtoMessage()    {}
func (*ServiceEndpoints) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce8e7107c99e043, []int{2}
}

func (m *ServiceEndpoints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceEndpoints.Unmarshal(m, b)
}
func (m *ServiceEndpoints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceEndpoints.Marshal(b, m, deterministic)
}
func (m *ServiceEndpoints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceEndpoints.Merge(m, src)
}
func (m *ServiceEndpoints) XXX_Size() int {
	return xxx_messageInfo_ServiceEndpoints.Size(m)
}
func (m *ServiceEndpoints) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceEndpoints.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceEndpoints proto.InternalMessageInfo

func (m *ServiceEndpoints) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ServiceEndpoints) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceEndpoints) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ServiceEndpoints) GetIPs() *ServiceIPs {
	if m != nil {
		return m.IPs
	}
	return nil
}

func (m *ServiceEndpoints) GetPorts() []*PortMapping {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *ServiceEndpoints) GetSubsets() []*EndpointsSubset {
	if m != nil {
		return m.Subsets
	}
	return nil
}

func (m *ServiceEndpoints) GetAllIPsV4() []string {
	if m != nil {
		return m.AllIPsV4
	}
	return nil
}

func (m *ServiceEndpoints) GetAllIPsV6() []string {
	if m != nil {
		return m.AllIPsV6
	}
	return nil
}

type ServiceIPs struct {
	ClusterIP            string   `protobuf:"bytes,1,opt,name=ClusterIP,proto3" json:"ClusterIP,omitempty"`
	ExternalIPs          []string `protobuf:"bytes,2,rep,name=ExternalIPs,proto3" json:"ExternalIPs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceIPs) Reset()         { *m = ServiceIPs{} }
func (m *ServiceIPs) String() string { return proto.CompactTextString(m) }
func (*ServiceIPs) ProtoMessage()    {}
func (*ServiceIPs) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce8e7107c99e043, []int{3}
}

func (m *ServiceIPs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceIPs.Unmarshal(m, b)
}
func (m *ServiceIPs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceIPs.Marshal(b, m, deterministic)
}
func (m *ServiceIPs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceIPs.Merge(m, src)
}
func (m *ServiceIPs) XXX_Size() int {
	return xxx_messageInfo_ServiceIPs.Size(m)
}
func (m *ServiceIPs) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceIPs.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceIPs proto.InternalMessageInfo

func (m *ServiceIPs) GetClusterIP() string {
	if m != nil {
		return m.ClusterIP
	}
	return ""
}

func (m *ServiceIPs) GetExternalIPs() []string {
	if m != nil {
		return m.ExternalIPs
	}
	return nil
}

type EndpointsSubset struct {
	// Ports ready on all the IPs in this definition
	Ports                []*Port  `protobuf:"bytes,1,rep,name=Ports,proto3" json:"Ports,omitempty"`
	IPsV4                []string `protobuf:"bytes,2,rep,name=IPsV4,proto3" json:"IPsV4,omitempty"`
	IPsV6                []string `protobuf:"bytes,3,rep,name=IPsV6,proto3" json:"IPsV6,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndpointsSubset) Reset()         { *m = EndpointsSubset{} }
func (m *EndpointsSubset) String() string { return proto.CompactTextString(m) }
func (*EndpointsSubset) ProtoMessage()    {}
func (*EndpointsSubset) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce8e7107c99e043, []int{4}
}

func (m *EndpointsSubset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointsSubset.Unmarshal(m, b)
}
func (m *EndpointsSubset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointsSubset.Marshal(b, m, deterministic)
}
func (m *EndpointsSubset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointsSubset.Merge(m, src)
}
func (m *EndpointsSubset) XXX_Size() int {
	return xxx_messageInfo_EndpointsSubset.Size(m)
}
func (m *EndpointsSubset) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointsSubset.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointsSubset proto.InternalMessageInfo

func (m *EndpointsSubset) GetPorts() []*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *EndpointsSubset) GetIPsV4() []string {
	if m != nil {
		return m.IPsV4
	}
	return nil
}

func (m *EndpointsSubset) GetIPsV6() []string {
	if m != nil {
		return m.IPsV6
	}
	return nil
}

type Port struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Protocol             Protocol `protobuf:"varint,2,opt,name=Protocol,proto3,enum=localnetv1.Protocol" json:"Protocol,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce8e7107c99e043, []int{5}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Port) GetProtocol() Protocol {
	if m != nil {
		return m.Protocol
	}
	return Protocol_UnknownProtocol
}

func (m *Port) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type PortMapping struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Protocol             Protocol `protobuf:"varint,2,opt,name=Protocol,proto3,enum=localnetv1.Protocol" json:"Protocol,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	NodePort             int32    `protobuf:"varint,4,opt,name=NodePort,proto3" json:"NodePort,omitempty"`
	TargetPort           int32    `protobuf:"varint,5,opt,name=TargetPort,proto3" json:"TargetPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PortMapping) Reset()         { *m = PortMapping{} }
func (m *PortMapping) String() string { return proto.CompactTextString(m) }
func (*PortMapping) ProtoMessage()    {}
func (*PortMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ce8e7107c99e043, []int{6}
}

func (m *PortMapping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortMapping.Unmarshal(m, b)
}
func (m *PortMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortMapping.Marshal(b, m, deterministic)
}
func (m *PortMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortMapping.Merge(m, src)
}
func (m *PortMapping) XXX_Size() int {
	return xxx_messageInfo_PortMapping.Size(m)
}
func (m *PortMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_PortMapping.DiscardUnknown(m)
}

var xxx_messageInfo_PortMapping proto.InternalMessageInfo

func (m *PortMapping) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PortMapping) GetProtocol() Protocol {
	if m != nil {
		return m.Protocol
	}
	return Protocol_UnknownProtocol
}

func (m *PortMapping) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *PortMapping) GetNodePort() int32 {
	if m != nil {
		return m.NodePort
	}
	return 0
}

func (m *PortMapping) GetTargetPort() int32 {
	if m != nil {
		return m.TargetPort
	}
	return 0
}

func init() {
	proto.RegisterEnum("localnetv1.Protocol", Protocol_name, Protocol_value)
	proto.RegisterType((*NextFilter)(nil), "localnetv1.NextFilter")
	proto.RegisterType((*NextItem)(nil), "localnetv1.NextItem")
	proto.RegisterType((*ServiceEndpoints)(nil), "localnetv1.ServiceEndpoints")
	proto.RegisterType((*ServiceIPs)(nil), "localnetv1.ServiceIPs")
	proto.RegisterType((*EndpointsSubset)(nil), "localnetv1.EndpointsSubset")
	proto.RegisterType((*Port)(nil), "localnetv1.Port")
	proto.RegisterType((*PortMapping)(nil), "localnetv1.PortMapping")
}

func init() { proto.RegisterFile("pkg/api/localnetv1/services.proto", fileDescriptor_2ce8e7107c99e043) }

var fileDescriptor_2ce8e7107c99e043 = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xdf, 0x6b, 0xd3, 0x50,
	0x14, 0x36, 0x4d, 0xea, 0xda, 0x53, 0x70, 0xe1, 0x5a, 0x34, 0xcc, 0x21, 0x35, 0x0f, 0x52, 0x06,
	0x6b, 0x66, 0x9c, 0x7d, 0x50, 0x10, 0xb4, 0x9b, 0x10, 0xd0, 0x12, 0x6e, 0x3b, 0x1f, 0x7c, 0x32,
	0x4d, 0x8f, 0x5d, 0x68, 0x9a, 0x84, 0xdc, 0x9b, 0xda, 0xfd, 0x37, 0x82, 0xff, 0xa8, 0xdc, 0x9b,
	0x25, 0xb9, 0xeb, 0xf0, 0x71, 0x6f, 0xe7, 0x7c, 0xdf, 0x77, 0x7e, 0xe5, 0xe4, 0x5c, 0x78, 0x95,
	0xad, 0x57, 0x4e, 0x90, 0x45, 0x4e, 0x9c, 0x86, 0x41, 0x9c, 0x20, 0xdf, 0xbe, 0x71, 0x18, 0xe6,
	0xdb, 0x28, 0x44, 0x36, 0xca, 0xf2, 0x94, 0xa7, 0x04, 0x1a, 0xca, 0xfe, 0x08, 0x30, 0xc5, 0x1d,
	0xff, 0x12, 0xc5, 0x1c, 0x73, 0xf2, 0x12, 0xc0, 0x4b, 0x18, 0x0f, 0x92, 0x10, 0xbd, 0x0b, 0x4b,
	0x1b, 0x68, 0x43, 0x83, 0x2a, 0x08, 0x31, 0x41, 0xa7, 0xb8, 0xb5, 0x5a, 0x92, 0x10, 0xa6, 0x9d,
	0x43, 0x47, 0xc4, 0x7b, 0x1c, 0x37, 0xe4, 0x04, 0x0c, 0x61, 0xcb, 0xb8, 0x9e, 0xfb, 0x6c, 0xd4,
	0x94, 0x19, 0x35, 0x35, 0xa8, 0xd4, 0x90, 0xf7, 0xd0, 0xbd, 0x4c, 0x96, 0x59, 0x1a, 0x25, 0x9c,
	0xc9, 0x7c, 0x3d, 0xf7, 0x58, 0x0d, 0x98, 0x95, 0x2d, 0xd7, 0x1a, 0xda, 0xc8, 0xed, 0x3f, 0x2d,
	0x30, 0xf7, 0x79, 0x72, 0x0c, 0xdd, 0x69, 0xb0, 0x41, 0x96, 0x05, 0x21, 0xca, 0x0e, 0xba, 0xb4,
	0x01, 0x08, 0x01, 0x43, 0x38, 0xb2, 0x52, 0x97, 0x4a, 0x5b, 0x60, 0xf3, 0x9b, 0x0c, 0x2d, 0xbd,
	0xc4, 0x84, 0x4d, 0x86, 0xa0, 0x7b, 0x3e, 0xb3, 0x96, 0xf7, 0x27, 0xb8, 0x2d, 0xe8, 0xf9, 0x8c,
	0x0a, 0x09, 0x39, 0x85, 0xb6, 0x9f, 0xe6, 0x9c, 0x59, 0x38, 0xd0, 0x87, 0x3d, 0xf7, 0xb9, 0xaa,
	0x15, 0xc4, 0xb7, 0x20, 0xcb, 0xa2, 0x64, 0x45, 0x4b, 0x15, 0x79, 0x07, 0x07, 0xb3, 0x62, 0xc1,
	0x90, 0x33, 0xeb, 0x97, 0x0c, 0x78, 0xa1, 0x06, 0xd4, 0x63, 0x94, 0x1a, 0x5a, 0x69, 0xc9, 0x11,
	0x74, 0x3e, 0xc5, 0xb1, 0xe7, 0xb3, 0xef, 0xe7, 0xd6, 0x6a, 0xa0, 0x0f, 0xbb, 0xb4, 0xf6, 0x15,
	0x6e, 0x6c, 0x5d, 0xdf, 0xe1, 0xc6, 0xf6, 0x57, 0x80, 0xa6, 0x61, 0xf1, 0x6d, 0x26, 0x71, 0xc1,
	0x38, 0xe6, 0x9e, 0x5f, 0x7d, 0x9b, 0x1a, 0x20, 0x03, 0xe8, 0x5d, 0xee, 0x38, 0xe6, 0x49, 0x20,
	0x82, 0xad, 0x96, 0x4c, 0xa5, 0x42, 0x36, 0xc2, 0xe1, 0x5e, 0x87, 0xe4, 0x75, 0x35, 0xbe, 0x26,
	0xa7, 0x31, 0xf7, 0xc7, 0xaf, 0xe6, 0xee, 0x43, 0xbb, 0xec, 0xbe, 0x4c, 0x5b, 0x3a, 0x15, 0x3a,
	0xb6, 0xf4, 0x06, 0x1d, 0xdb, 0x3f, 0xc1, 0x10, 0x41, 0xf5, 0xb2, 0x34, 0x65, 0x59, 0x67, 0xd0,
	0xf1, 0xc5, 0xcf, 0x1b, 0xa6, 0xb1, 0x5c, 0xe2, 0x13, 0xb7, 0x7f, 0xa7, 0xe4, 0x2d, 0x47, 0x6b,
	0x95, 0xc8, 0x22, 0xb2, 0xc9, 0xf5, 0xb6, 0xa9, 0xb4, 0xed, 0xbf, 0x1a, 0xf4, 0x94, 0xe5, 0x3c,
	0x5c, 0x25, 0xb1, 0x9c, 0x69, 0xba, 0x44, 0x89, 0x1b, 0x12, 0xaf, 0x7d, 0x71, 0x65, 0xf3, 0x20,
	0x5f, 0x21, 0x97, 0x6c, 0x5b, 0xb2, 0x0a, 0x72, 0xf2, 0xa1, 0xe9, 0x80, 0x3c, 0x85, 0xc3, 0xab,
	0x64, 0x9d, 0xa4, 0xbf, 0x93, 0x0a, 0x32, 0x1f, 0x91, 0x03, 0xd0, 0xe7, 0x13, 0xdf, 0xd4, 0x84,
	0x71, 0x75, 0xe1, 0x9b, 0x2d, 0xd2, 0x01, 0x63, 0x36, 0x99, 0xfb, 0xa6, 0xee, 0x4e, 0x94, 0xc3,
	0x22, 0xe3, 0xf2, 0x22, 0xc9, 0x7f, 0x6e, 0xf1, 0xa8, 0xbf, 0x8f, 0x8b, 0x3b, 0x3e, 0xd3, 0x3e,
	0x9f, 0xff, 0x70, 0x57, 0x11, 0xbf, 0x2e, 0x16, 0xa3, 0x30, 0xdd, 0x38, 0x9b, 0x30, 0x2e, 0x18,
	0x06, 0x85, 0xb3, 0x2e, 0x16, 0x78, 0x9a, 0xe5, 0xe9, 0xee, 0xc6, 0x75, 0xee, 0x3f, 0x33, 0x8b,
	0xc7, 0xf2, 0x79, 0x79, 0xfb, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xab, 0x3b, 0xcf, 0x46, 0x83, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EndpointsClient is the client API for Endpoints service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EndpointsClient interface {
	// Returns all the endpoints for this node.
	Next(ctx context.Context, in *NextFilter, opts ...grpc.CallOption) (Endpoints_NextClient, error)
}

type endpointsClient struct {
	cc *grpc.ClientConn
}

func NewEndpointsClient(cc *grpc.ClientConn) EndpointsClient {
	return &endpointsClient{cc}
}

func (c *endpointsClient) Next(ctx context.Context, in *NextFilter, opts ...grpc.CallOption) (Endpoints_NextClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Endpoints_serviceDesc.Streams[0], "/localnetv1.Endpoints/Next", opts...)
	if err != nil {
		return nil, err
	}
	x := &endpointsNextClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Endpoints_NextClient interface {
	Recv() (*NextItem, error)
	grpc.ClientStream
}

type endpointsNextClient struct {
	grpc.ClientStream
}

func (x *endpointsNextClient) Recv() (*NextItem, error) {
	m := new(NextItem)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EndpointsServer is the server API for Endpoints service.
type EndpointsServer interface {
	// Returns all the endpoints for this node.
	Next(*NextFilter, Endpoints_NextServer) error
}

func RegisterEndpointsServer(s *grpc.Server, srv EndpointsServer) {
	s.RegisterService(&_Endpoints_serviceDesc, srv)
}

func _Endpoints_Next_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NextFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EndpointsServer).Next(m, &endpointsNextServer{stream})
}

type Endpoints_NextServer interface {
	Send(*NextItem) error
	grpc.ServerStream
}

type endpointsNextServer struct {
	grpc.ServerStream
}

func (x *endpointsNextServer) Send(m *NextItem) error {
	return x.ServerStream.SendMsg(m)
}

var _Endpoints_serviceDesc = grpc.ServiceDesc{
	ServiceName: "localnetv1.Endpoints",
	HandlerType: (*EndpointsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Next",
			Handler:       _Endpoints_Next_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/api/localnetv1/services.proto",
}
