name: local up KPNG
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GO_VERSION: "1.19"

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
    - name: setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Install dependencies
      run: |
        go version
        go install golang.org/x/lint/golint@master

  local-up-kpng:
    name: local-up-kpng
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 30  #Guys is 30 minutes ok, or too much? Currently on Github runners it takes 5m 30s
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: KPNG local up 
      run: ./hack/kpng-local-up.sh

